# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
permalink: /blog/:year/:month/:day/:title

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title
gems:
- jekyll-compass

#Prose
prose:
  siteurl: "http://eowise.com"
  metadata:
    _projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "name"
        field:
          label: "Name"
          element: "text"
      - name: "shorter"
        field:
          label: "Shorter"
          element: "textarea"
